arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/l10n/generated
output-class: AppLocalizations
synthetic-package: false
untranslated-messages-file: lib/l10n/untranslated_messages.txt
nullable-getter: false
