// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9KzbuXkOcGi_nDYvCjHfdP8DxlrkplE',
    appId: '1:970538144554:web:10f21f826b37f1aaae0453',
    messagingSenderId: '970538144554',
    projectId: 'anystep-community-services',
    authDomain: 'anystep-community-services.firebaseapp.com',
    storageBucket: 'anystep-community-services.firebasestorage.app',
    measurementId: 'G-KBCCPZ0DV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDswFJkFyPk1U8yQjXKaQ8Hkg3O9RdBveQ',
    appId: '1:970538144554:android:44b9979dca1952bcae0453',
    messagingSenderId: '970538144554',
    projectId: 'anystep-community-services',
    storageBucket: 'anystep-community-services.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ2gdrm9yITzf-h_St9UnByX2UIHnt9b8',
    appId: '1:970538144554:ios:8a8e10f59628080dae0453',
    messagingSenderId: '970538144554',
    projectId: 'anystep-community-services',
    storageBucket: 'anystep-community-services.firebasestorage.app',
    iosBundleId: 'com.example.anystep',
  );
}
